### ISSUE TITLE
Headings for Children of Components do not work

### ISSUE THREAD

**Issue by nikischin** [shuding/nextra#3749]
**Describe the bug**

Headings for children of imported documents do not work as expected. They behave very strange.

**To Reproduce**

Sample files

```
import Template from "./template.mdx";

<Template someProp="someValue">
    ## Subheading from Child should be inbetween second and third heading

    Some Text from child
</Template >
```

Template:
```
# Title of Imported file

Someprop has {props.someProp}

## First Heading of Imported file

Some Text of Imported file

## Second Heading of Imported file

Some Text of Imported file

Children is below this

{props.children}

## Third Heading of Imported file

Some Text of Imported file

## Fourth Heading of Imported file

Some Text of Imported file
```

**Expected behavior** 

Children with heading should be inbetween other headings of parent imported file.

**Screenshots** 
<img width="907" alt="Bildschirmfoto 2024-11-29 um 18 15 42" src="https://github.com/user-attachments/assets/26265d9b-3353-4bf1-ba79-e5a8cbc8d346">

**Desktop:**

- OS: macOS
- Browser Safari
- Version 18.1.1

**Comment by nikischin** [comment]
Also it will crash if props are used within headings:

```
## Someheading containing {props.someProp}
```

Will produce an error like this:
```
Cannot read properties of undefined (reading 'props.someProp')
...
export function useTOC(props) {
  13 |   return [{
> 14 |     value: <>{"Someheading containing "}{props.someProp}</>,
```

Should I open a separate ticket for this?

**Comment by nikischin** [comment]
Generally headings in combination with embedded documents do not work well.

Even if I use something like

```
import TemplateWithoutChild from "./template.mdx";

<TemplateWithoutChild />

## Some other Heading outside template
This is displayed correctly in the sidebar but the heading is not displayed correctly in the content (The first heading of the Template is displayed instead here which should not be the case.
```

This does work for the sidebar but not the content itself.

**Comment by dimaMachina** [comment]
> **Describe the bug**
> 
> Headings for children of imported documents do not work as expected. They behave very strange.
> 
> **To Reproduce**
> 
> **sample.mdx**
> 
> ```
> import Template from "./template.mdx";
> 
> <Template someProp="someValue">
>     ## Subheading from Child should be inbetween second and third heading
> 
>     Some Text from child
> </Template>
> ```
> 
> **template.mdx**
> 
> ```
> # Title of Imported file
> 
> Someprop has {props.someProp}
> 
> ## First Heading of Imported file
> 
> Some Text of Imported file
> 
> ## Second Heading of Imported file
> 
> Some Text of Imported file
> 
> Children is below this
> 
> {props.children}
> 
> ## Third Heading of Imported file
> 
> Some Text of Imported file
> 
> ## Fourth Heading of Imported file
> 
> Some Text of Imported file
> ```
> 
> **Expected behavior**
> 
> Children with heading should be inbetween other headings of parent imported file.
> 
> **Screenshots** <img alt="Bildschirmfoto 2024-11-29 um 18 15 42" width="907" src="https://private-user-images.githubusercontent.com/49103409/391155723-26265d9b-3353-4bf1-ba79-e5a8cbc8d346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMjk3OTQsIm5iZiI6MTczMzAyOTQ5NCwicGF0aCI6Ii80OTEwMzQwOS8zOTExNTU3MjMtMjYyNjVkOWItMzM1My00YmYxLWJhNzktZTVhOGNiYzhkMzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDA1MDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwODFkZTNjOTFiN2IyZjdlODk3ODU0NDgzMDllNTQxNWI2ZDUxZGU1MjZkNGQzMjEyYTE4N2FiOGQ5OGRlN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JT6D0YXGlLwyMynIxNTxp3B_ZL6UYtZnro0KKIQp_4U">
> 
> **Desktop:**
> 
> * OS: macOS
> * Browser Safari
> * Version 18.1.1

I think this hidden bug was fixed in Nextra 4 in https://github.com/shuding/nextra/pull/3698/files 
<img width="721" alt="image" src="https://github.com/user-attachments/assets/e20c42c5-52f4-4e1f-9c81-860fc3eefdf6">

**Comment by nikischin** [comment]
Hi @dimaMachina, thank you so much for your investigation and answer!

I totally understand your focus already is on v4, and I also followed your other threads on it. However I wasn't able to find the blog post for migration you were talking about, so I haven't yet started migration. Would you have a link for me to the blog post maybe? I would be happy to try the new version soon!

**Comment by dimaMachina** [comment]
Did’t yet post, I am on vacation and there is some new missing features to document

**Comment by nikischin** [comment]
> Did’t yet post, I am on vacation and there is some new missing features to document

Ah no worries! Enjoy your vacation and happy to see some update after you are back. Thank you so much for still checking Github issues during vacation!

**Comment by nikischin** [comment]
@dimaMachina 
> I think this hidden bug was fixed in Nextra 4 in https://github.com/shuding/nextra/pull/3698/files 
> 
> <img width="721" alt="image" src="https://github.com/user-attachments/assets/e20c42c5-52f4-4e1f-9c81-860fc3eefdf6">
> 
> 

Unfortunately this bug still persists in v4.

**Comment by dimaMachina** [comment]
Hi, feel free to share a reproduction, so it could be fixed

**Comment by nikischin** [comment]
> Hi, feel free to share a reproduction, so it could be fixed 

What kind of production would you prefer? 

I did put some sample data in the issue description already, if you have a sample codesandbox I should clone and modify to reproduce let me know.

Thank you so much!
